version: 2.0.0-beta04-{build}
init:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"
  - ps: .\dotnet-install.ps1 -Version 1.0.0-preview2-003121
  - ps: Remove-Item .\dotnet-install.ps1
build_script:
  - ps: .\build.ps1
test_script:
  - ps: .\test.ps1
after_build:
  - ps: .\pack.ps1
  - ps: $root = Resolve-Path .\MoreLinq\bin\Release; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }